# Load the data

In [1]:
import pandas as pd

#Load datasets
reviews = pd.read_csv("../data/reviews83325.csv")
places = pd.read_csv("../data/Tripadvisor.csv")

print("Reviews shape:", reviews.shape)
print("Places shape:", places.shape)

C:\Users\geoff\AppData\Local\Temp\ipykernel_43148\797032139.py:4: DtypeWarning: Columns (15,16,17,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews = pd.read_csv("../data/reviews83325.csv")

Reviews shape: (340385, 21)
Places shape: (3761, 60)

In [11]:
reviews.head(2)

,id,idplace,titre,idauteur,review,note,date_review,date_visit,langue,published_platform,...,subratings,machine_translated,machine_translatable,owner_id,owner_langue,owner_date_review,owner_connection,owner_responder,owner_response,owner_title
0,771569620,188467,February,F645CC9429E8A40EB1F5A487780EC683,Personally I think it is the most beautiful sq...,5,23/9/2020 11:14:11,2020-02,en,Desktop,...,[],False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,769814072,188467,Nice green square,AFFB511F21DF819776CB2F8013034382,We walked through this lovely park but did not...,4,11/9/2020 07:52:32,2019-10,en,Desktop,...,[],False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340385 entries, 0 to 340384
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    340385 non-null  int64
 1   idplace               340385 non-null  int64
 2   titre                 340382 non-null  object
 3   idauteur              339726 non-null  object
 4   review                340385 non-null  object
 5   note                  340385 non-null  int64
 6   date_review           340385 non-null  object
 7   date_visit            321147 non-null  object
 8   langue                340385 non-null  object
 9   published_platform    340385 non-null  object
 10  typeReview            340385 non-null  object
 11  subratings            340385 non-null  object
 12  machine_translated    340385 non-null  bool
 13  machine_translatable  340385 non-null  bool
 14  owner_id              39641 non-null   float64
 15  owner_langue          39641 non-null   object
 16  owner_date_review     39641 non-null   object
 17  owner_connection      39640 non-null   object
 18  owner_responder       39397 non-null   object
 19  owner_response        39641 non-null   object
 20  owner_title           39641 non-null   object
dtypes: bool(2), float64(1), int64(3), object(15)
memory usage: 50.0+ MB

In [13]:
places.head(2)

,id,idTrip,fromId,nom,url,rating,nbAvis,nbAvisRecupere,latitude,longitude,...,ap_exclusion,ap_inclusions,ap_introduction,ap_primary_supplier_attraction_id,ap_primary_supplier_subtype,ap_primary_ta_geo_id,ap_product_code,ap_product_highlights,ap_product_text,ap_raw
0,188467,187147.0,187070.0,Place des Vosges,https://www.tripadvisor.fr/Attraction_Review-g...,4.108407,5663,5664.0,48.855614,2.365553,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,188468,187147.0,187070.0,Rue des Francs Bourgeois,https://www.tripadvisor.fr/Attraction_Review-g...,3.316532,73,73.0,48.858140,2.359880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
places.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3761 entries, 0 to 3760
Data columns (total 60 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   id                                 3761 non-null   int64
 1   idTrip                             3754 non-null   float64
 2   fromId                             201 non-null    float64
 3   nom                                3761 non-null   object
 4   url                                3697 non-null   object
 5   rating                             3661 non-null   float64
 6   nbAvis                             3761 non-null   int64
 7   nbAvisRecupere                     2344 non-null   float64
 8   latitude                           3761 non-null   float64
 9   longitude                          3761 non-null   float64
 10  typeR                              3761 non-null   object
 11  adresse                            1028 non-null   object
 12  priceRange                         586 non-null    object
 13  closed                             1092 non-null   float64
 14  hotelType                          57 non-null     object
 15  hotelStyle                         0 non-null      float64
 16  hotelStars                         0 non-null      float64
 17  hotelRoomNumber                    3761 non-null   int64
 18  hotelNoteEmplacement               0 non-null      float64
 19  hotelNoteProprete                  0 non-null      float64
 20  hotelNoteService                   0 non-null      float64
 21  HotelNoteQualitePrix               0 non-null      float64
 22  hoteldistance                      58 non-null     float64
 23  hotelbearing                       64 non-null     object
 24  restaurantTypeCuisine              518 non-null    object
 25  restaurantDietaryRestrictions      232 non-null    object
 26  restaurantMeals                    0 non-null      float64
 27  restaurantFeatures                 0 non-null      float64
 28  restaurantNoteCuisine              0 non-null      float64
 29  restaurantNoteService              0 non-null      float64
 30  restaurantNoteQualitePrix          0 non-null      float64
 31  restaurantNoteAmbiance             0 non-null      float64
 32  activiteType                       3021 non-null   object
 33  activiteSubCategorie               405 non-null    object
 34  activiteSubType                    405 non-null    object
 35  website                            768 non-null    object
 36  nbScanReview                       0 non-null      float64
 37  dateLastScanReviews                2344 non-null   object
 38  shape_gid                          3761 non-null   int64
 39  gadm36_gid                         3761 non-null   int64
 40  hotelprice                         2983 non-null   object
 41  hotelBookingID                     45 non-null     float64
 42  restaurantSubcategory              484 non-null    object
 43  restaurantType                     623 non-null    object
 44  ap_additional_info                 2669 non-null   object
 45  ap_age_band_list                   2669 non-null   object
 46  ap_attraction_ids                  2669 non-null   object
 47  ap_booking_question_list           2669 non-null   object
 48  ap_bubble_rating_integer           2669 non-null   float64
 49  ap_duration                        2669 non-null   object
 50  ap_exclusion                       2103 non-null   object
 51  ap_inclusions                      2667 non-null   object
 52  ap_introduction                    2669 non-null   object
 53  ap_primary_supplier_attraction_id  2669 non-null   float64
 54  ap_primary_supplier_subtype        2631 non-null   object
 55  ap_primary_ta_geo_id               2669 non-null   float64
 56  ap_product_code                    2669 non-null   object
 57  ap_product_highlights              1121 non-null   object
 58  ap_product_text                    2669 non-null   object
 59  ap_raw                             2669 non-null   object
dtypes: float64(25), int64(5), object(30)
memory usage: 1.7+ MB

# Filter English Reviews Only

In [16]:
reviews_en = reviews[reviews["langue"] == "en"]
print("English reviews shape:", reviews_en.shape)

English reviews shape: (153071, 21)

# Merge Reviews with Places

we join: 
- reviews.idplace
- places.id

In [18]:
data = reviews_en.merge(places,
                        left_on="idplace",
                        right_on="id",
                        how="inner")

print("Merged dataset shape:", data.shape)

Merged dataset shape: (153071, 81)

Now each review is linked to its place information

Need to check if this merge actually works well or if some data is lost

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153071 entries, 0 to 153070
Data columns (total 81 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   id_x                               153071 non-null  int64
 1   idplace                            153071 non-null  int64
 2   titre                              153070 non-null  object
 3   idauteur                           153061 non-null  object
 4   review                             153071 non-null  object
 5   note                               153071 non-null  int64
 6   date_review                        153071 non-null  object
 7   date_visit                         142576 non-null  object
 8   langue                             153071 non-null  object
 9   published_platform                 153071 non-null  object
 10  typeReview                         153071 non-null  object
 11  subratings                         153071 non-null  object
 12  machine_translated                 153071 non-null  bool
 13  machine_translatable               153071 non-null  bool
 14  owner_id                           19136 non-null   float64
 15  owner_langue                       19136 non-null   object
 16  owner_date_review                  19136 non-null   object
 17  owner_connection                   19136 non-null   object
 18  owner_responder                    19056 non-null   object
 19  owner_response                     19136 non-null   object
 20  owner_title                        19136 non-null   object
 21  id_y                               153071 non-null  int64
 22  idTrip                             153071 non-null  float64
 23  fromId                             56458 non-null   float64
 24  nom                                153071 non-null  object
 25  url                                139350 non-null  object
 26  rating                             152739 non-null  float64
 27  nbAvis                             153071 non-null  int64
 28  nbAvisRecupere                     153071 non-null  float64
 29  latitude                           153071 non-null  float64
 30  longitude                          153071 non-null  float64
 31  typeR                              153071 non-null  object
 32  adresse                            114571 non-null  object
 33  priceRange                         57394 non-null   object
 34  closed                             128292 non-null  float64
 35  hotelType                          13721 non-null   object
 36  hotelStyle                         0 non-null       float64
 37  hotelStars                         0 non-null       float64
 38  hotelRoomNumber                    153071 non-null  int64
 39  hotelNoteEmplacement               0 non-null       float64
 40  hotelNoteProprete                  0 non-null       float64
 41  hotelNoteService                   0 non-null       float64
 42  HotelNoteQualitePrix               0 non-null       float64
 43  hoteldistance                      13721 non-null   float64
 44  hotelbearing                       13721 non-null   object
 45  restaurantTypeCuisine              43706 non-null   object
 46  restaurantDietaryRestrictions      31975 non-null   object
 47  restaurantMeals                    0 non-null       float64
 48  restaurantFeatures                 0 non-null       float64
 49  restaurantNoteCuisine              0 non-null       float64
 50  restaurantNoteService              0 non-null       float64
 51  restaurantNoteQualitePrix          0 non-null       float64
 52  restaurantNoteAmbiance             0 non-null       float64
 53  activiteType                       94814 non-null   object
 54  activiteSubCategorie               70059 non-null   object
 55  activiteSubType                    70059 non-null   object
 56  website                            104942 non-null  object
 57  nbScanReview                       0 non-null       float64
 58  dateLastScanReviews                153071 non-null  object
 59  shape_gid                          153071 non-null  int64
 60  gadm36_gid                         153071 non-null  int64
 61  hotelprice                         63491 non-null   object
 62  hotelBookingID                     11717 non-null   float64
 63  restaurantSubcategory              43448 non-null   object
 64  restaurantType                     44512 non-null   object
 65  ap_additional_info                 24779 non-null   object
 66  ap_age_band_list                   24779 non-null   object
 67  ap_attraction_ids                  24779 non-null   object
 68  ap_booking_question_list           24779 non-null   object
 69  ap_bubble_rating_integer           24779 non-null   float64
 70  ap_duration                        24779 non-null   object
 71  ap_exclusion                       23562 non-null   object
 72  ap_inclusions                      24779 non-null   object
 73  ap_introduction                    24779 non-null   object
 74  ap_primary_supplier_attraction_id  24779 non-null   float64
 75  ap_primary_supplier_subtype        24368 non-null   object
 76  ap_primary_ta_geo_id               24779 non-null   float64
 77  ap_product_code                    24779 non-null   object
 78  ap_product_highlights              22956 non-null   object
 79  ap_product_text                    24779 non-null   object
 80  ap_raw                             24779 non-null   object
dtypes: bool(2), float64(26), int64(8), object(45)
memory usage: 92.6+ MB

# Aggregate Reviews by Place

we want one document per place

Need to change this, so it includes commas to be able to select reviews, or remove and do later after review selection

In [22]:
grouped = data.groupby("idplace")["review"].apply(lambda x: " ".join(x)).reset_index()
grouped.columns = ["place_id", "full_text_reviews"]

print("Number of uniques places:", len(grouped))
grouped.head()

Number of uniques places: 1835

   place_id                                  full_text_reviews
0    188467  Personally I think it is the most beautiful sq...
1    188468  My old college friend and I booked this beauti...
2    188470  Being winter and all, not a lot going on, howe...
3    188471  To call Au Passe Partout a shop is a serious u...
4    188472  Very old historical place. I attended to exper...

Now:
- One row = One place
- All reviews concatenated into one large text

# Add metadata (For Evaluation Only)

we keep metadata for later evaluation (NOT for model training)

In [26]:
metadata_cols = [
    "id",
    "typeR",
    "activiteSubCategorie",
    "activiteSubType",
    "restaurantType",
    "restaurantTypeCuisine",
    "priceRange"
]

metadata = places[metadata_cols]

final_dataset = grouped.merge(
    metadata,
    left_on="place_id",
    right_on="id",
    how="left"
)

print("Final dataset shape:", final_dataset.shape)
final_dataset.head()

Final dataset shape: (1835, 9)

,place_id,full_text_reviews,id,typeR,activiteSubCategorie,activiteSubType,restaurantType,restaurantTypeCuisine,priceRange
0,188467,Personally I think it is the most beautiful sq...,188467,A,47,163,NaN,NaN,NaN
1,188468,My old college friend and I booked this beauti...,188468,A,47,163,NaN,NaN,NaN
2,188470,"Being winter and all, not a lot going on, howe...",188470,A,"26,47,51","34,144",NaN,NaN,NaN
3,188471,To call Au Passe Partout a shop is a serious u...,188471,A,26,137,NaN,NaN,NaN
4,188472,Very old historical place. I attended to exper...,188472,A,47,10,NaN,NaN,NaN

# Quick Exploratory Analysis

Distribution of places types

In [28]:
print(final_dataset["typeR"].value_counts())

typeR
AP    989
R     538
A     252
H      56
Name: count, dtype: int64

Text length statistics

In [29]:
final_dataset["text_length"] = final_dataset["full_text_reviews"].apply(lambda x: len(x.split()))
print(final_dataset["text_length"].describe())

count    1.835000e+03
mean     6.677538e+03
std      4.871902e+04
min      1.700000e+01
25%      1.505000e+02
50%      5.750000e+02
75%      2.763000e+03
max      1.896322e+06
Name: text_length, dtype: float64

This will show:
- Minimum number of words
- Maximum number of words
- Average document length